//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int Id { get; set; }
        public string Tabla { get; set; }
        public string CodigoRegistro { get; set; }
        public string Accion { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string ValoresAntiguos { get; set; }
        public string ValoresNuevos { get; set; }
    }
}
