//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Texto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public short Estado { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
