//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego_Plataforma
    {
        public int Id { get; set; }
        public Nullable<int> JuegoId { get; set; }
        public Nullable<int> PlataformaId { get; set; }
        public short Estado { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Plataforma Plataforma { get; set; }
    }
}
