//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFEntities : DbContext
    {
        public BDFEntities()
            : base("name=BDFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Calificacion> Calificacion { get; set; }
        public virtual DbSet<Coleccion> Coleccion { get; set; }
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Intercambio> Intercambio { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Item_Genero> Item_Genero { get; set; }
        public virtual DbSet<Juego_Plataforma> Juego_Plataforma { get; set; }
        public virtual DbSet<Plataforma> Plataforma { get; set; }
        public virtual DbSet<Prestamo> Prestamo { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
